version: '3.8'

services:
  mongodb:
    container_name: yapi-mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - my-network
  yapi:
    container_name: yapi-server
    build:
      context: ./
      dockerfile: Dockerfile
    # 第一次启动使用
    command: "yapi server"
    ports:
      - 9090:9090
    # 安装成功后运行
    # command: "node /my-yapi/vendors/server/app.js"
    # ports:
    #   - 3000:3000
    volumes:
      - ./my-yapi:/my-yapi
    depends_on:
      - mongodb
    networks:
      - my-network
networks:
  my-network:
